### ISSUE TITLE
How to remove all .dll from application folder

### ISSUE THREAD

**Issue by Th3AnG3L** [cydolo/CyberReverse#4]
Hello,
How to remove all .dll's that were copy to project Debug folder,
To leave only Bunifu_1.5.3.dll that is cracked to be in project, how can i make that.
Or it needs additional cracking to combine everything inside the 1.5.3.dll ?

**Comment by cydolo** [comment]
I think you're using something completely different. The Bunifu.Licensing.dll file has been rewritten so that all security checks are bypassed. Only this file was changed and not the components.

You have to merge all dll's so that only your software is in the debug folder without references. 
take a look at [Costura.Fody](https://github.com/Fody/Costura)
